apps/customers/urls.py
from django.urls import path
from .views import (
    customer_list,
    customer_detail,
    CustomerCreateView,
    CustomerAccountDepositView,
    customer_account_detail,
)

app_name = 'customers'

urlpatterns = [
    path('', customer_list, name='customer_list'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customer/<int:pk>/', customer_detail, name='customer_detail'),
    path('customer/account/<int:pk>/', customer_account_detail, name='customer_account'),
    path('customer/account/<int:pk>/deposit/', CustomerAccountDepositView.as_view(), name='customer_account_deposit'),
]

apps/orders/urls.py
from django.urls import path
from .import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

apps/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_index, name='shop_index'),
    path('products/', views.product_list, name='product_list'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),

    path('panier/', views.cart_detail, name='cart_detail'),
    path('panier/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('panier/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('customers/', include('apps.customers.urls', namespace='customsers')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('', include("apps.shop.urls", namespace='shop')),
    path("accounts/", include("apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")), # django built-in auth
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/shop/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    created_date = models.DateField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)

    class Meta:
        ordering = ('name',)
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id])

    def __str__(self):
        return self.name

apps/shop/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

apps/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Product
from apps.customers.models import Customer
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm


@login_required
def shop_index(request):
    # Count the number of products in the databse
    product_count = Product.objects.count()
    # Count the number of customers in the database
    customer_count = Customer.objects.count()

    context = {
    #    'products': products,
        'product_count': product_count,
        'customer_count': customer_count,
    }

    return render(request, 'shop/shop_index.html', context)


@login_required
def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }

    return render(request, 'shop/product_list.html', context)


@login_required
def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    cart_product_form = CartAddProductForm()

    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }

    return render(request, 'shop/product_detail.html', context)


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('shop:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('shop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                                        'quantity': item['quantity'],
                                        'override': True})
    return render(request, 'shop/cart_detail.html', {'cart': cart})

apps/shop/templates/shop/cart_detail.html
{% extends "dashboard_base.html" %}
{% load static %}
{% block title %} Panier {% endblock %}
{% block content %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Panier</h1>
    <a class="small" href="{% url 'shop:product_list' %}">Retour à la liste des produits</a>
</div>
    <!-- Panier -->
    <div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" class="cart">
        <thead>
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
                <th>Remove</th>
                <th>Prix Unitaire</th>
                <th>Sous-Total</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
        {% with product=item.product %}
        <tr>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url 'shop:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input class="btn btn-primary" type="submit" value="Update">
                </form>
            </td>
            <td>
                <form action="{% url 'shop:cart_remove' product.id %}" method="post">
                    <input class="btn btn-danger" type="submit" value="Remove">
                    {% csrf_token %}
                </form>
            </td>
            <td class="num">£ {{ item.price }}</td>
            <td class="num">£ {{ item.total_price }}</td>
        </tr>
        {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="3"></td>
            <td style="display: none;"></td>
            <td style="display: none;"></td>
            <td class="num">£ {{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    </div>
    </div>
    
    <p>
        <a href="{% url 'shop:product_list' %}" class="btn btn-default">Continuer saisie</a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-primary">Aller à facture</a>
    </p>
{% endblock %}

apps/shop/templates/shop/product_detail.html
{% extends "dashboard_base.html" %}
{% block title %} {{ product.name }} {% endblock title %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Détail Du Produit</h1>
    <a class="small" href="{% url 'shop:product_list' %}">Retour à la liste des produits</a>
</div>
<div class="row">
            <!-- Card Product Detail -->
            <div class="col-lg-6">
                <div class="card border-bottom-dark h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-md font-weight-bold text-dark text-uppercase mb-1">
                                    {{ product.name }}</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Prix: {{ product.price }} £</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-pound-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                        <!-- Divider -->
                        <hr class="sidebar-divider d-none d-md-block">
                        <form action="{% url 'shop:cart_add' product.id %}" method="post">
                            {{ cart_product_form }}
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Ajouter au panier">
                        </form>
                    </div>
                </div>
            </div>
</div>
{% endblock content %}

apps/shop/templates/shop/product_list.html
{% extends "dashboard_base.html" %}
{% block title %} Les produits {% endblock title %}
{% block content %}
<!--Page Heading-->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Produits</h1>
    <!--<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
</div>

<nav class="mt-4 mb-4 rounded" aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-2 rounded mb-0">
        <li class="breadcrumb-item"><a href="{% url 'shop:shop_index' %}">Dashboard</a></li>
        <!--<li class="breadcrumb-item active">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    Contenu Du Panier:
                    <a href="{% url 'shop:cart_detail' %}">
                        {{ total_items }} produit{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Le Panier est vide.
                {% endif %}
            {% endwith %}        
        </li>-->
    </ol>
</nav>
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Liste des produits</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Produit</th>
                        <th>Prix unitaire</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Produit</th>
                        <th>Prix unitaire</th>
                    </tr>
                </tfoot>
                <tbody>
                {% for product in products %}
                    <tr>
                        <td><a href="{{ product.get_absolute_url }}"> {{ product.name }} </a></td>
                        <td>£ {{ product.price }} </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End DataTable -->    
{% endblock content %}

apps/shop/templates/shop/shop_index.html
{% extends "dashboard_base.html" %}
{% block title %} Dashboard {% endblock title %}
{% block content %}
<!--Page Heading-->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <!--<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
</div>
<!--Content Row-->
<div class="row">

    <!-- Total Products Card -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <a href="{% url 'shop:product_list' %}">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Nombre total de produits
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ product_count }}</div>
                        </a>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Total Customers Card -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <a href="{% url 'customers:customer_list' %}">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Nombre total de clients
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ customer_count }}</div>
                        </a>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

                        <!-- Earnings (Monthly) Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-info shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                                            </div>
                                            <div class="row no-gutters align-items-center">
                                                <div class="col-auto">
                                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                                </div>
                                                <div class="col">
                                                    <div class="progress progress-sm mr-2">
                                                        <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Pending Requests Card Example -->
                        <div class="col-xl-3 col-md-6 mb-4">
                            <div class="card border-left-warning shadow h-100 py-2">
                                <div class="card-body">
                                    <div class="row no-gutters align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                                Pending Requests</div>
                                            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                                        </div>
                                        <div class="col-auto">
                                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock content %}