apps/customers/urls.py
from django.urls import path
from .views import (
    customer_list,
    customer_detail,
    CustomerCreateView,
    CustomerAccountDepositView,
    customer_account_detail,
)

app_name = 'customers'

urlpatterns = [
    path('', customer_list, name='customer_list'),
    path('customers/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customer/<int:pk>/', customer_detail, name='customer_detail'),
    path('customer/account/<int:pk>/', customer_account_detail, name='customer_account'),
    path('customer/account/<int:pk>/deposit/', CustomerAccountDepositView.as_view(), name='customer_account_deposit'),
]

apps/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_index, name='shop_index'),
    path('products/', views.product_list, name='product_list'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),

    path('panier/', views.cart_detail, name='cart_detail'),
    path('panier/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('panier/remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('customers/', include('apps.customers.urls', namespace='customsers')),
    path('orders/', include('apps.orders.urls', namespace='orders')),
    path('', include("apps.shop.urls", namespace='shop')),
    path("accounts/", include("apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")), # django built-in auth
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/customers/models.py
from decimal import Decimal
from django.db import models
from django.urls import reverse


class Customer(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    email = models.EmailField(max_length=50, unique=True)
    created_date = models.DateField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)

    class Meta:
        ordering = ('name',)
    
    def get_absolute_url(self):
        return reverse('customers:customer_detail', args=[self.pk])
    
    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return 0

    def __str__(self):
        return self.email
    

class CustomerAccount(models.Model):
    customer = models.OneToOneField(
        Customer,
        related_name='account',
        related_query_name='account',
        on_delete=models.CASCADE
    )
    account_no = models.PositiveIntegerField(unique=True)
    balance = models.DecimalField(
        default=0,
        max_digits=5,
        decimal_places=2
    )

    def get_absolute_url(self):
        return reverse('customers:customer_account', args=[self.pk])

    def __str__(self):
        return str(self.account_no)
    

class CustomerAccountDeposit(models.Model):
    """
    Model to register customers' deposits.
    """
    account = models.ForeignKey(
        CustomerAccount,
        related_name='deposits',
        on_delete=models.CASCADE
    )
    amount = models.DecimalField(
        max_digits=5,
        decimal_places=2
    )
    timestamp = models.DateTimeField(auto_now_add=True)

apps/customers/forms.py
from django import forms
from django.conf import settings
from django.db import transaction

from .models import Customer, CustomerAccount, CustomerAccountDeposit


class CustomerCreationForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        fields = [
            'name',
            'email',
        ]
    
    @transaction.atomic # This to guarantee that either all of the transaction succeeds or none of it does.
    def save(self, commit=True):
        customer = super().save(commit=False)
        if commit:
            customer.save()

            CustomerAccount.objects.create(
                customer=customer,
                account_no=(
                    customer.id + settings.ACCOUNT_NUMBER_START_FROM
                )
            )


class CustomerAccountDepositForm(forms.ModelForm):
    """
    Form to handle Customer's deposit
    """
    class Meta:
        model = CustomerAccountDeposit
        fields = ['amount',]

    def save(self, commit=True):
        return super().save()

apps/customers/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView

from .models import Customer, CustomerAccount, CustomerAccountDeposit
from .forms import CustomerCreationForm, CustomerAccountDepositForm#, TransactionDateRangeForm


class CustomerCreateView(LoginRequiredMixin, CreateView):
    """
    CBV to create a new Customer.
    """
    model = Customer
    form_class = CustomerCreationForm
    template_name = 'customers/customer/create.html'

    def get_success_url(self):
        return reverse_lazy('customers:customer_list')


@login_required
def customer_list(request):
    customers = Customer.objects.all()
    context = {
        'customers': customers,
    }

    return render(request, 'customers/customer_list.html', context)


@login_required
def customer_detail(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    #customer_account = get_object_or_404(CustomerAccount, pk=pk)
    customer_account = CustomerAccount.objects.get(pk=customer.account.id)
    #cart_product_form = CartAddProductForm()

    context = {
        'customer': customer,
        'customer_account': customer_account,
    #    'cart_product_form': cart_product_form
    }

    return render(request, 'customers/customer_detail.html', context)


@login_required
def customer_account_detail(request, pk):
    customer_account = get_object_or_404(CustomerAccount, pk=pk)

    context = {
        'customer_account': customer_account,
    }

    return render(request, 'customers/account_detail.html', context)


class CustomerAccountDepositView(LoginRequiredMixin, CreateView):
    model = CustomerAccountDeposit
    form_class = CustomerAccountDepositForm
    template_name = 'customers/deposit/create.html'

    def get_context_data(self, **kwargs):
        context = super(CustomerAccountDepositView, self).get_context_data(**kwargs)
        context['account'] = get_object_or_404(CustomerAccount, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        form.instance.account = get_object_or_404(CustomerAccount, pk=self.kwargs['pk'])

        form.instance.account.balance += amount
        form.instance.account.save(
            update_fields=[
#                'initial_deposit_date',
                'balance'
            ]
        )

        return super(CustomerAccountDepositView, self).form_valid(form)

    def get_success_url(self):
        return reverse('customers:customer_account', kwargs={'pk': self.kwargs['pk'], })

apps/customers/templates/customers/account_detail.html
{% extends "dashboard_base.html" %}
{% block title %} {{ customer.name }} {% endblock title %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Détail Du Client</h1>
    <a class="small" href="{% url 'customers:customer_list' %}">Retour à la liste des clients</a>
</div>
<div class="row">
            <!-- Card Customer Detail -->
            <div class="col-lg-6">
                <div class="card border-bottom-dark h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-md font-weight-bold text-dark text-uppercase mb-1">
                                    Nom: {{ customer.name }}
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Email: {{ customer.email }}</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Solde: {{ customer.balance }} £</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-pound-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                        <!-- Divider -->
                        <hr class="sidebar-divider d-none d-md-block">
                        <a class="btn btn-primary" href="{% url 'customers:customer_account_deposit' customer_account.id %}">Recharger compte</a>
                    </div>
                </div>
            </div>
</div>
{% endblock content %}

apps/customers/templates/customers/customer_detail.html
{% extends "dashboard_base.html" %}
{% block title %} {{ customer.name }} {% endblock title %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Détail Du Client</h1>
    <a class="small" href="{% url 'customers:customer_list' %}">Retour à la liste des clients</a>
</div>
<div class="row">
            <!-- Card Customer Detail -->
            <div class="col-lg-6">
                <div class="card border-bottom-dark h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-md font-weight-bold text-dark text-uppercase mb-1">
                                    Nom: {{ customer.name }}
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Email: {{ customer.email }}</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">Solde: {{ customer.balance }} £</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-pound-sign fa-2x text-gray-300"></i>
                            </div>
                        </div>
                        <!-- Divider -->
                        <hr class="sidebar-divider d-none d-md-block">
                        <a class="btn btn-primary" href="{{ customer_account.get_absolute_url }}">Compte</a>
                    </div>
                </div>
            </div>
</div>
{% endblock content %}

apps/customers/templates/customers/customer_list.html
{% extends "dashboard_base.html" %}
{% block title %} Les clients {% endblock title %}
{% block content %}
<!--Page Heading-->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Clients</h1>
    <!--<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>-->
</div>

<nav class="mt-4 mb-4 rounded" aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-2 rounded mb-0">
        <li class="breadcrumb-item"><a href="{% url 'customers:customer_create' %}">Créer client</a></li>
        <!--<li class="breadcrumb-item active">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    Contenu Du Panier:
                    <a href="{% url 'shop:cart_detail' %}">
                        {{ total_items }} produit{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Le Panier est vide.
                {% endif %}
            {% endwith %}        
        </li>-->
    </ol>
</nav>
<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Liste des clients</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Email</th>
                        <th>Solde</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Nom</th>
                        <th>Email</th>
                        <th>Solde</th>
                    </tr>
                </tfoot>
                <tbody>
                {% for customer in customers %}
                    <tr>
                        <td><a href="{{ customer.get_absolute_url }}"> {{ customer.name }} </a></td>
                        <td>{{ customer.email }} </td>
                        <td>£ {{ customer.balance }} </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End DataTable -->    
{% endblock content %}